// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: concord/badge/query.proto

package badge

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Params_FullMethodName           = "/concord.badge.Query/Params"
	Query_GetBadge_FullMethodName         = "/concord.badge.Query/GetBadge"
	Query_GetBadgesByOwner_FullMethodName = "/concord.badge.Query/GetBadgesByOwner"
	Query_GetSeriesByOwner_FullMethodName = "/concord.badge.Query/GetSeriesByOwner"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of GetBadge items.
	GetBadge(ctx context.Context, in *QueryGetBadgeRequest, opts ...grpc.CallOption) (*QueryGetBadgeResponse, error)
	// Queries a list of GetBadgesByOwner items.
	GetBadgesByOwner(ctx context.Context, in *QueryGetBadgesByOwnerRequest, opts ...grpc.CallOption) (*QueryGetBadgesByOwnerResponse, error)
	// Queries a list of GetSeriesByOwner items.
	GetSeriesByOwner(ctx context.Context, in *QueryGetSeriesByOwnerRequest, opts ...grpc.CallOption) (*QueryGetSeriesByOwnerResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetBadge(ctx context.Context, in *QueryGetBadgeRequest, opts ...grpc.CallOption) (*QueryGetBadgeResponse, error) {
	out := new(QueryGetBadgeResponse)
	err := c.cc.Invoke(ctx, Query_GetBadge_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetBadgesByOwner(ctx context.Context, in *QueryGetBadgesByOwnerRequest, opts ...grpc.CallOption) (*QueryGetBadgesByOwnerResponse, error) {
	out := new(QueryGetBadgesByOwnerResponse)
	err := c.cc.Invoke(ctx, Query_GetBadgesByOwner_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetSeriesByOwner(ctx context.Context, in *QueryGetSeriesByOwnerRequest, opts ...grpc.CallOption) (*QueryGetSeriesByOwnerResponse, error) {
	out := new(QueryGetSeriesByOwnerResponse)
	err := c.cc.Invoke(ctx, Query_GetSeriesByOwner_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of GetBadge items.
	GetBadge(context.Context, *QueryGetBadgeRequest) (*QueryGetBadgeResponse, error)
	// Queries a list of GetBadgesByOwner items.
	GetBadgesByOwner(context.Context, *QueryGetBadgesByOwnerRequest) (*QueryGetBadgesByOwnerResponse, error)
	// Queries a list of GetSeriesByOwner items.
	GetSeriesByOwner(context.Context, *QueryGetSeriesByOwnerRequest) (*QueryGetSeriesByOwnerResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) GetBadge(context.Context, *QueryGetBadgeRequest) (*QueryGetBadgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBadge not implemented")
}
func (UnimplementedQueryServer) GetBadgesByOwner(context.Context, *QueryGetBadgesByOwnerRequest) (*QueryGetBadgesByOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBadgesByOwner not implemented")
}
func (UnimplementedQueryServer) GetSeriesByOwner(context.Context, *QueryGetSeriesByOwnerRequest) (*QueryGetSeriesByOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSeriesByOwner not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetBadge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetBadgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetBadge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetBadge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetBadge(ctx, req.(*QueryGetBadgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetBadgesByOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetBadgesByOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetBadgesByOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetBadgesByOwner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetBadgesByOwner(ctx, req.(*QueryGetBadgesByOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetSeriesByOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetSeriesByOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetSeriesByOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GetSeriesByOwner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetSeriesByOwner(ctx, req.(*QueryGetSeriesByOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "concord.badge.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetBadge",
			Handler:    _Query_GetBadge_Handler,
		},
		{
			MethodName: "GetBadgesByOwner",
			Handler:    _Query_GetBadgesByOwner_Handler,
		},
		{
			MethodName: "GetSeriesByOwner",
			Handler:    _Query_GetSeriesByOwner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "concord/badge/query.proto",
}
