// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: concord/badge/query.proto

package types

import (
	context "context"
	nft "cosmossdk.io/x/nft"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf80493b604c5304, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf80493b604c5304, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetBadgeRequest struct {
	SeriesId string `protobuf:"bytes,1,opt,name=seriesId,proto3" json:"seriesId,omitempty"`
	BadgeId  string `protobuf:"bytes,2,opt,name=badgeId,proto3" json:"badgeId,omitempty"`
}

func (m *QueryGetBadgeRequest) Reset()         { *m = QueryGetBadgeRequest{} }
func (m *QueryGetBadgeRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetBadgeRequest) ProtoMessage()    {}
func (*QueryGetBadgeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf80493b604c5304, []int{2}
}
func (m *QueryGetBadgeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetBadgeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetBadgeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetBadgeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetBadgeRequest.Merge(m, src)
}
func (m *QueryGetBadgeRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetBadgeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetBadgeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetBadgeRequest proto.InternalMessageInfo

func (m *QueryGetBadgeRequest) GetSeriesId() string {
	if m != nil {
		return m.SeriesId
	}
	return ""
}

func (m *QueryGetBadgeRequest) GetBadgeId() string {
	if m != nil {
		return m.BadgeId
	}
	return ""
}

type QueryGetBadgeResponse struct {
	Badge *Badge `protobuf:"bytes,1,opt,name=badge,proto3" json:"badge,omitempty"`
}

func (m *QueryGetBadgeResponse) Reset()         { *m = QueryGetBadgeResponse{} }
func (m *QueryGetBadgeResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetBadgeResponse) ProtoMessage()    {}
func (*QueryGetBadgeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf80493b604c5304, []int{3}
}
func (m *QueryGetBadgeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetBadgeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetBadgeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetBadgeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetBadgeResponse.Merge(m, src)
}
func (m *QueryGetBadgeResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetBadgeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetBadgeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetBadgeResponse proto.InternalMessageInfo

func (m *QueryGetBadgeResponse) GetBadge() *Badge {
	if m != nil {
		return m.Badge
	}
	return nil
}

type QueryGetBadgesByOwnerRequest struct {
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (m *QueryGetBadgesByOwnerRequest) Reset()         { *m = QueryGetBadgesByOwnerRequest{} }
func (m *QueryGetBadgesByOwnerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetBadgesByOwnerRequest) ProtoMessage()    {}
func (*QueryGetBadgesByOwnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf80493b604c5304, []int{4}
}
func (m *QueryGetBadgesByOwnerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetBadgesByOwnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetBadgesByOwnerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetBadgesByOwnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetBadgesByOwnerRequest.Merge(m, src)
}
func (m *QueryGetBadgesByOwnerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetBadgesByOwnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetBadgesByOwnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetBadgesByOwnerRequest proto.InternalMessageInfo

func (m *QueryGetBadgesByOwnerRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type QueryGetBadgesByOwnerResponse struct {
	Badges []*Badge `protobuf:"bytes,1,rep,name=badges,proto3" json:"badges,omitempty"`
}

func (m *QueryGetBadgesByOwnerResponse) Reset()         { *m = QueryGetBadgesByOwnerResponse{} }
func (m *QueryGetBadgesByOwnerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetBadgesByOwnerResponse) ProtoMessage()    {}
func (*QueryGetBadgesByOwnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf80493b604c5304, []int{5}
}
func (m *QueryGetBadgesByOwnerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetBadgesByOwnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetBadgesByOwnerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetBadgesByOwnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetBadgesByOwnerResponse.Merge(m, src)
}
func (m *QueryGetBadgesByOwnerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetBadgesByOwnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetBadgesByOwnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetBadgesByOwnerResponse proto.InternalMessageInfo

func (m *QueryGetBadgesByOwnerResponse) GetBadges() []*Badge {
	if m != nil {
		return m.Badges
	}
	return nil
}

type QueryGetSeriesByOwnerRequest struct {
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (m *QueryGetSeriesByOwnerRequest) Reset()         { *m = QueryGetSeriesByOwnerRequest{} }
func (m *QueryGetSeriesByOwnerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetSeriesByOwnerRequest) ProtoMessage()    {}
func (*QueryGetSeriesByOwnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf80493b604c5304, []int{6}
}
func (m *QueryGetSeriesByOwnerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSeriesByOwnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSeriesByOwnerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSeriesByOwnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSeriesByOwnerRequest.Merge(m, src)
}
func (m *QueryGetSeriesByOwnerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSeriesByOwnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSeriesByOwnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSeriesByOwnerRequest proto.InternalMessageInfo

func (m *QueryGetSeriesByOwnerRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type QueryGetSeriesByOwnerResponse struct {
	Series []*nft.Class `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty"`
}

func (m *QueryGetSeriesByOwnerResponse) Reset()         { *m = QueryGetSeriesByOwnerResponse{} }
func (m *QueryGetSeriesByOwnerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetSeriesByOwnerResponse) ProtoMessage()    {}
func (*QueryGetSeriesByOwnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf80493b604c5304, []int{7}
}
func (m *QueryGetSeriesByOwnerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSeriesByOwnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSeriesByOwnerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSeriesByOwnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSeriesByOwnerResponse.Merge(m, src)
}
func (m *QueryGetSeriesByOwnerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSeriesByOwnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSeriesByOwnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSeriesByOwnerResponse proto.InternalMessageInfo

func (m *QueryGetSeriesByOwnerResponse) GetSeries() []*nft.Class {
	if m != nil {
		return m.Series
	}
	return nil
}

type QueryGetBadgesBySeriesRequest struct {
	Series string `protobuf:"bytes,1,opt,name=series,proto3" json:"series,omitempty"`
}

func (m *QueryGetBadgesBySeriesRequest) Reset()         { *m = QueryGetBadgesBySeriesRequest{} }
func (m *QueryGetBadgesBySeriesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetBadgesBySeriesRequest) ProtoMessage()    {}
func (*QueryGetBadgesBySeriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf80493b604c5304, []int{8}
}
func (m *QueryGetBadgesBySeriesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetBadgesBySeriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetBadgesBySeriesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetBadgesBySeriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetBadgesBySeriesRequest.Merge(m, src)
}
func (m *QueryGetBadgesBySeriesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetBadgesBySeriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetBadgesBySeriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetBadgesBySeriesRequest proto.InternalMessageInfo

func (m *QueryGetBadgesBySeriesRequest) GetSeries() string {
	if m != nil {
		return m.Series
	}
	return ""
}

type QueryGetBadgesBySeriesResponse struct {
	Badges []*Badge `protobuf:"bytes,1,rep,name=badges,proto3" json:"badges,omitempty"`
}

func (m *QueryGetBadgesBySeriesResponse) Reset()         { *m = QueryGetBadgesBySeriesResponse{} }
func (m *QueryGetBadgesBySeriesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetBadgesBySeriesResponse) ProtoMessage()    {}
func (*QueryGetBadgesBySeriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf80493b604c5304, []int{9}
}
func (m *QueryGetBadgesBySeriesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetBadgesBySeriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetBadgesBySeriesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetBadgesBySeriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetBadgesBySeriesResponse.Merge(m, src)
}
func (m *QueryGetBadgesBySeriesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetBadgesBySeriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetBadgesBySeriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetBadgesBySeriesResponse proto.InternalMessageInfo

func (m *QueryGetBadgesBySeriesResponse) GetBadges() []*Badge {
	if m != nil {
		return m.Badges
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "concord.badge.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "concord.badge.QueryParamsResponse")
	proto.RegisterType((*QueryGetBadgeRequest)(nil), "concord.badge.QueryGetBadgeRequest")
	proto.RegisterType((*QueryGetBadgeResponse)(nil), "concord.badge.QueryGetBadgeResponse")
	proto.RegisterType((*QueryGetBadgesByOwnerRequest)(nil), "concord.badge.QueryGetBadgesByOwnerRequest")
	proto.RegisterType((*QueryGetBadgesByOwnerResponse)(nil), "concord.badge.QueryGetBadgesByOwnerResponse")
	proto.RegisterType((*QueryGetSeriesByOwnerRequest)(nil), "concord.badge.QueryGetSeriesByOwnerRequest")
	proto.RegisterType((*QueryGetSeriesByOwnerResponse)(nil), "concord.badge.QueryGetSeriesByOwnerResponse")
	proto.RegisterType((*QueryGetBadgesBySeriesRequest)(nil), "concord.badge.QueryGetBadgesBySeriesRequest")
	proto.RegisterType((*QueryGetBadgesBySeriesResponse)(nil), "concord.badge.QueryGetBadgesBySeriesResponse")
}

func init() { proto.RegisterFile("concord/badge/query.proto", fileDescriptor_bf80493b604c5304) }

var fileDescriptor_bf80493b604c5304 = []byte{
	// 633 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0x41, 0x6f, 0xd3, 0x30,
	0x18, 0x86, 0x9b, 0xa1, 0x85, 0xcd, 0x08, 0x89, 0x99, 0x0e, 0x6d, 0xd1, 0x96, 0x41, 0x00, 0x69,
	0x2a, 0x23, 0x56, 0x4b, 0x61, 0x08, 0xc1, 0xa5, 0x3b, 0xa0, 0x49, 0xc0, 0xa0, 0xdc, 0xb8, 0x54,
	0x49, 0xeb, 0x85, 0x48, 0x6b, 0x9c, 0xc5, 0xee, 0xa0, 0xaa, 0x7a, 0xe1, 0x17, 0x20, 0xc1, 0x9d,
	0x2b, 0x5c, 0x10, 0x3f, 0x63, 0xc7, 0x49, 0x5c, 0x38, 0x21, 0xd4, 0x22, 0xf1, 0x37, 0x50, 0xec,
	0x2f, 0x65, 0x49, 0x9b, 0xae, 0xe2, 0x92, 0xda, 0xf1, 0xeb, 0xf7, 0x7b, 0xfc, 0xf5, 0x75, 0xd0,
	0x6a, 0x93, 0x05, 0x4d, 0x16, 0xb5, 0x88, 0xeb, 0xb4, 0x3c, 0x4a, 0x0e, 0x3b, 0x34, 0xea, 0xda,
	0x61, 0xc4, 0x04, 0xc3, 0x17, 0x61, 0xc9, 0x96, 0x4b, 0xc6, 0x92, 0xd3, 0xf6, 0x03, 0x46, 0xe4,
	0x53, 0x29, 0x8c, 0xa2, 0xc7, 0x3c, 0x26, 0x87, 0x24, 0x1e, 0xc1, 0xdb, 0x35, 0x8f, 0x31, 0xef,
	0x80, 0x12, 0x27, 0xf4, 0x89, 0x13, 0x04, 0x4c, 0x38, 0xc2, 0x67, 0x01, 0x87, 0xd5, 0x52, 0x93,
	0xf1, 0x36, 0xe3, 0xc4, 0x75, 0x38, 0x94, 0x23, 0x47, 0x65, 0x97, 0x0a, 0xa7, 0x4c, 0x42, 0xc7,
	0xf3, 0x03, 0x29, 0x06, 0xad, 0x91, 0x86, 0x0b, 0x9d, 0xc8, 0x69, 0x27, 0x3e, 0x19, 0x70, 0xf9,
	0x4c, 0x00, 0xa0, 0x44, 0xb0, 0x2f, 0x46, 0xde, 0xc1, 0xbe, 0x50, 0xab, 0x56, 0x11, 0xe1, 0x17,
	0x71, 0xd9, 0xe7, 0xd2, 0xad, 0x4e, 0x0f, 0x3b, 0x94, 0x0b, 0x6b, 0x0f, 0x5d, 0x4e, 0xbd, 0xe5,
	0x21, 0x0b, 0x38, 0xc5, 0xf7, 0x91, 0xae, 0xaa, 0xae, 0x68, 0x57, 0xb5, 0xcd, 0x0b, 0x95, 0x65,
	0x3b, 0xd5, 0x14, 0x5b, 0xc9, 0x6b, 0x8b, 0xc7, 0x3f, 0x37, 0x0a, 0x9f, 0xff, 0x7c, 0x2b, 0x69,
	0x75, 0xd0, 0x5b, 0x4f, 0x50, 0x51, 0x1a, 0x3e, 0xa6, 0xa2, 0x16, 0x4b, 0xa1, 0x10, 0x36, 0xd0,
	0x02, 0xa7, 0x91, 0x4f, 0xf9, 0x6e, 0x4b, 0x7a, 0x2e, 0xd6, 0x47, 0x73, 0xbc, 0x82, 0xce, 0x4b,
	0xdb, 0xdd, 0xd6, 0xca, 0x9c, 0x5c, 0x4a, 0xa6, 0xd6, 0x0e, 0x5a, 0xce, 0xb8, 0x01, 0x60, 0x09,
	0xcd, 0x4b, 0x0d, 0xf0, 0x15, 0x33, 0x7c, 0x4a, 0xac, 0x24, 0x56, 0x15, 0xad, 0xa5, 0x4c, 0x78,
	0xad, 0xbb, 0xf7, 0x26, 0xa0, 0x51, 0x82, 0x56, 0x44, 0xf3, 0x2c, 0x9e, 0x03, 0x97, 0x9a, 0x58,
	0x4f, 0xd1, 0x7a, 0xce, 0x2e, 0x40, 0xd8, 0x42, 0xba, 0xf4, 0x8f, 0x7b, 0x74, 0x2e, 0x97, 0x01,
	0x34, 0xa7, 0x21, 0x5e, 0xca, 0x73, 0xcf, 0x04, 0x51, 0xff, 0x07, 0x91, 0xd9, 0x05, 0x10, 0x65,
	0xa4, 0xab, 0x36, 0x02, 0xc4, 0xaa, 0xad, 0x42, 0x60, 0xc7, 0x7f, 0x3c, 0x84, 0xc0, 0xde, 0x39,
	0x70, 0x38, 0xaf, 0x83, 0xd0, 0xda, 0x1e, 0x3f, 0x98, 0xf2, 0x4e, 0x50, 0xae, 0x9c, 0xf2, 0x8c,
	0x59, 0x92, 0x8d, 0xcf, 0x90, 0x99, 0xb7, 0xf1, 0x7f, 0x5a, 0x52, 0xf9, 0xa4, 0xa3, 0x79, 0x69,
	0x88, 0x8f, 0x90, 0xae, 0x12, 0x85, 0xaf, 0x65, 0x76, 0x8c, 0x47, 0xd6, 0xb0, 0xa6, 0x49, 0x14,
	0x88, 0x75, 0xf3, 0xdd, 0xf7, 0xdf, 0x1f, 0xe6, 0x36, 0xf0, 0x3a, 0x89, 0xb5, 0x51, 0x20, 0xc8,
	0xa4, 0x2b, 0x85, 0x3f, 0x6a, 0x68, 0x21, 0x39, 0x0d, 0xbe, 0x3e, 0xc9, 0x37, 0x13, 0x63, 0xe3,
	0xc6, 0x74, 0x11, 0x94, 0x7f, 0x24, 0xcb, 0x6f, 0xe3, 0xbb, 0x39, 0xe5, 0x3d, 0x2a, 0x1a, 0x6a,
	0xd4, 0x4b, 0x2e, 0x41, 0x9f, 0xf4, 0x20, 0xf4, 0x7d, 0xfc, 0x45, 0x43, 0x97, 0xb2, 0xb1, 0xc3,
	0xb7, 0xa6, 0x55, 0xce, 0xa4, 0xc9, 0xd8, 0x9a, 0x4d, 0x0c, 0xb8, 0x0f, 0x24, 0x6e, 0x15, 0x57,
	0xce, 0xc2, 0xe5, 0x0d, 0xb7, 0xdb, 0x90, 0xc9, 0x24, 0x3d, 0xf9, 0x33, 0x62, 0x4d, 0xa5, 0x33,
	0x97, 0x75, 0x52, 0xf2, 0x73, 0x59, 0x27, 0x06, 0x7e, 0x26, 0x56, 0xd5, 0xd3, 0x71, 0xd6, 0xaf,
	0x1a, 0x5a, 0x1a, 0x0b, 0x2f, 0x3e, 0xab, 0x57, 0xa9, 0xcb, 0x61, 0xdc, 0x9e, 0x51, 0x0d, 0xb8,
	0x0f, 0x25, 0xee, 0x3d, 0x5c, 0x9d, 0xa9, 0xb5, 0x0a, 0x3c, 0x09, 0x45, 0xbf, 0x56, 0x3b, 0x1e,
	0x98, 0xda, 0xc9, 0xc0, 0xd4, 0x7e, 0x0d, 0x4c, 0xed, 0xfd, 0xd0, 0x2c, 0x9c, 0x0c, 0xcd, 0xc2,
	0x8f, 0xa1, 0x59, 0x78, 0xb5, 0xe9, 0xf9, 0xe2, 0x75, 0xc7, 0xb5, 0x9b, 0xac, 0x3d, 0xe6, 0xfc,
	0x16, 0xbc, 0x45, 0x37, 0xa4, 0xdc, 0xd5, 0xe5, 0xe7, 0xff, 0xce, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xa6, 0xea, 0xa0, 0x81, 0xf2, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of GetBadge items.
	GetBadge(ctx context.Context, in *QueryGetBadgeRequest, opts ...grpc.CallOption) (*QueryGetBadgeResponse, error)
	// Queries a list of GetBadgesByOwner items.
	GetBadgesByOwner(ctx context.Context, in *QueryGetBadgesByOwnerRequest, opts ...grpc.CallOption) (*QueryGetBadgesByOwnerResponse, error)
	// Queries a list of GetSeriesByOwner items.
	GetSeriesByOwner(ctx context.Context, in *QueryGetSeriesByOwnerRequest, opts ...grpc.CallOption) (*QueryGetSeriesByOwnerResponse, error)
	// Queries a list of GetBadgesBySeries items.
	GetBadgesBySeries(ctx context.Context, in *QueryGetBadgesBySeriesRequest, opts ...grpc.CallOption) (*QueryGetBadgesBySeriesResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/concord.badge.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetBadge(ctx context.Context, in *QueryGetBadgeRequest, opts ...grpc.CallOption) (*QueryGetBadgeResponse, error) {
	out := new(QueryGetBadgeResponse)
	err := c.cc.Invoke(ctx, "/concord.badge.Query/GetBadge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetBadgesByOwner(ctx context.Context, in *QueryGetBadgesByOwnerRequest, opts ...grpc.CallOption) (*QueryGetBadgesByOwnerResponse, error) {
	out := new(QueryGetBadgesByOwnerResponse)
	err := c.cc.Invoke(ctx, "/concord.badge.Query/GetBadgesByOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetSeriesByOwner(ctx context.Context, in *QueryGetSeriesByOwnerRequest, opts ...grpc.CallOption) (*QueryGetSeriesByOwnerResponse, error) {
	out := new(QueryGetSeriesByOwnerResponse)
	err := c.cc.Invoke(ctx, "/concord.badge.Query/GetSeriesByOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetBadgesBySeries(ctx context.Context, in *QueryGetBadgesBySeriesRequest, opts ...grpc.CallOption) (*QueryGetBadgesBySeriesResponse, error) {
	out := new(QueryGetBadgesBySeriesResponse)
	err := c.cc.Invoke(ctx, "/concord.badge.Query/GetBadgesBySeries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of GetBadge items.
	GetBadge(context.Context, *QueryGetBadgeRequest) (*QueryGetBadgeResponse, error)
	// Queries a list of GetBadgesByOwner items.
	GetBadgesByOwner(context.Context, *QueryGetBadgesByOwnerRequest) (*QueryGetBadgesByOwnerResponse, error)
	// Queries a list of GetSeriesByOwner items.
	GetSeriesByOwner(context.Context, *QueryGetSeriesByOwnerRequest) (*QueryGetSeriesByOwnerResponse, error)
	// Queries a list of GetBadgesBySeries items.
	GetBadgesBySeries(context.Context, *QueryGetBadgesBySeriesRequest) (*QueryGetBadgesBySeriesResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) GetBadge(ctx context.Context, req *QueryGetBadgeRequest) (*QueryGetBadgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBadge not implemented")
}
func (*UnimplementedQueryServer) GetBadgesByOwner(ctx context.Context, req *QueryGetBadgesByOwnerRequest) (*QueryGetBadgesByOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBadgesByOwner not implemented")
}
func (*UnimplementedQueryServer) GetSeriesByOwner(ctx context.Context, req *QueryGetSeriesByOwnerRequest) (*QueryGetSeriesByOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSeriesByOwner not implemented")
}
func (*UnimplementedQueryServer) GetBadgesBySeries(ctx context.Context, req *QueryGetBadgesBySeriesRequest) (*QueryGetBadgesBySeriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBadgesBySeries not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/concord.badge.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetBadge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetBadgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetBadge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/concord.badge.Query/GetBadge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetBadge(ctx, req.(*QueryGetBadgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetBadgesByOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetBadgesByOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetBadgesByOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/concord.badge.Query/GetBadgesByOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetBadgesByOwner(ctx, req.(*QueryGetBadgesByOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetSeriesByOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetSeriesByOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetSeriesByOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/concord.badge.Query/GetSeriesByOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetSeriesByOwner(ctx, req.(*QueryGetSeriesByOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetBadgesBySeries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetBadgesBySeriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetBadgesBySeries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/concord.badge.Query/GetBadgesBySeries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetBadgesBySeries(ctx, req.(*QueryGetBadgesBySeriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "concord.badge.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetBadge",
			Handler:    _Query_GetBadge_Handler,
		},
		{
			MethodName: "GetBadgesByOwner",
			Handler:    _Query_GetBadgesByOwner_Handler,
		},
		{
			MethodName: "GetSeriesByOwner",
			Handler:    _Query_GetSeriesByOwner_Handler,
		},
		{
			MethodName: "GetBadgesBySeries",
			Handler:    _Query_GetBadgesBySeries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "concord/badge/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetBadgeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetBadgeRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetBadgeRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BadgeId) > 0 {
		i -= len(m.BadgeId)
		copy(dAtA[i:], m.BadgeId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.BadgeId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SeriesId) > 0 {
		i -= len(m.SeriesId)
		copy(dAtA[i:], m.SeriesId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.SeriesId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetBadgeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetBadgeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetBadgeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Badge != nil {
		{
			size, err := m.Badge.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetBadgesByOwnerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetBadgesByOwnerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetBadgesByOwnerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetBadgesByOwnerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetBadgesByOwnerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetBadgesByOwnerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Badges) > 0 {
		for iNdEx := len(m.Badges) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Badges[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetSeriesByOwnerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSeriesByOwnerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSeriesByOwnerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetSeriesByOwnerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSeriesByOwnerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSeriesByOwnerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Series) > 0 {
		for iNdEx := len(m.Series) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Series[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetBadgesBySeriesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetBadgesBySeriesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetBadgesBySeriesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Series) > 0 {
		i -= len(m.Series)
		copy(dAtA[i:], m.Series)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Series)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetBadgesBySeriesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetBadgesBySeriesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetBadgesBySeriesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Badges) > 0 {
		for iNdEx := len(m.Badges) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Badges[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetBadgeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SeriesId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.BadgeId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetBadgeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Badge != nil {
		l = m.Badge.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetBadgesByOwnerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetBadgesByOwnerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Badges) > 0 {
		for _, e := range m.Badges {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryGetSeriesByOwnerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetSeriesByOwnerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Series) > 0 {
		for _, e := range m.Series {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryGetBadgesBySeriesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Series)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetBadgesBySeriesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Badges) > 0 {
		for _, e := range m.Badges {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetBadgeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetBadgeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetBadgeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SeriesId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SeriesId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BadgeId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BadgeId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetBadgeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetBadgeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetBadgeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Badge", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Badge == nil {
				m.Badge = &Badge{}
			}
			if err := m.Badge.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetBadgesByOwnerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetBadgesByOwnerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetBadgesByOwnerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetBadgesByOwnerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetBadgesByOwnerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetBadgesByOwnerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Badges", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Badges = append(m.Badges, &Badge{})
			if err := m.Badges[len(m.Badges)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSeriesByOwnerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSeriesByOwnerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSeriesByOwnerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSeriesByOwnerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSeriesByOwnerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSeriesByOwnerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Series", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Series = append(m.Series, &nft.Class{})
			if err := m.Series[len(m.Series)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetBadgesBySeriesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetBadgesBySeriesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetBadgesBySeriesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Series", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Series = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetBadgesBySeriesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetBadgesBySeriesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetBadgesBySeriesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Badges", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Badges = append(m.Badges, &Badge{})
			if err := m.Badges[len(m.Badges)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
